collage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('posts.urls')),
    #url(r'^posts/', include('posts.urls' , namespace="posts")),
    #url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^profile/myprofile$', views.myprofile, name='profile'),
    url(r'^profile/update$', views.update_profile, name='update_profile'),
    url(r'^profile/(?P<username>[-\w]+)/$', views.user_profile, name='user_profile'),
    url(r'^$', views.question_list, name='question_list'),
    url(r'^add_question/$', views.add_question, name='add_question'),
    url(r'^post/(?P<pk>\d+)/$', views.question_detail, name='question_detail'),
    url(r'^post/(?P<pk>\d+)/delete/$', views.delete_question, name='delete_question'),
    url(r'^post/(?P<pk>\d+)/answer/$', views.add_answer, name='add_answer'),
    url(r'^post/(?P<pk>\d+)/answer/edit/$', views.update_answer, name='update_answer'),
    url(r'^post/(?P<pk>\d+)/answer/delete/$', views.delete_answer, name='delete_answer'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.update_question, name='update_question'),

    #url(r'^$', views.post_list, name='post_list'),
    #url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from ckeditor.fields import RichTextField #does not contain upload option for us in Images
from ckeditor_uploader.fields import  RichTextUploadingField #for adding upload from our own server in CKEDITOR

import datetime

# Create your models here.
#user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,default=1)
class Profile(models.Model):
    GENDER_CHOICES = (
        ('Male','M'),
        ('Female','F' ),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE,default=1)
    bio  = models.CharField(blank=True, max_length=200,null=True)
    gender = models.CharField(max_length=128, choices=GENDER_CHOICES,null=True,blank=True)
    dob = models.DateTimeField(blank=True, null=True)
    image = models.FileField(null=True,default='Images/No-img.jpg')
    #image  = models.ImageField(upload_to="Images/",default='Images/No-img.jpg',null=True)


    def get_date(self):
        return self.modified.date()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    slug = models.SlugField(max_length=255, null=True, blank=True)
    details = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(blank=True, null=True)
#    class Meta:
#        db_table = "questions"
#        verbose_name = ("Question")
#        verbose_name_plural = ("Questions")
#        ordering = ("created_date",)
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.text
    

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = RichTextUploadingField()
#    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

#    class Meta:
#        db_table = "answers"
#        verbose_name = ("Answer")
#        verbose_name_plural = ("Answers")
#        ordering = ("date",)

#    def __unicode__(self):
#        return u'{0} - {1}'.format(self.user.username, self.question.title)

#    def get_comment_as_markdown(self):
#        return markdown.markdown(self.comment, safe_mode='escape')

#    def get_up_voters(self):
#        upvotes = UserUpvote.objects.filter(comment=self)
#        upvote_users = [upvote.user.id for upvote in upvotes]
#        return upvote_users
class Comment(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)

posts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Answer, Question, Comment
from django.conf import settings
from django.forms.widgets import DateInput, SelectDateWidget


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

class ProfileForm(forms.ModelForm):
    GENDER_CHOICES = (
        ('Male','Male'),
        ('Female','Female' ),
    )
    dob = forms.DateField(widget=SelectDateWidget(
        empty_label=("Choose Year", "Choose Month", "Choose Day"),
    ))
    gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect)

    class Meta:
        model = Profile
        fields = ('bio', 'dob', 'image','gender')


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = ('text',)

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('text','details',)
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.utils import timezone
from django.contrib.auth.models import User

from .models import Profile, Question, Answer, Comment
from .forms import UserForm, ProfileForm, AnswerForm, QuestionForm
# Create your views here.
#user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,default=1)
#LockFeature.objects.create(user=request.user ,has_lock=False)
#lockfeature = get_object_or_404(LockFeature,user=request.user)
def myprofile(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('account_login'))
    else:
        user = request.user

        return render(request, 'posts/profile.html',{'user':user})

def user_profile(request,username):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('account_login'))
    else:
        users = get_object_or_404(User,username=username)
        return render(request, 'posts/userprofile.html',{'users':users})



def update_profile(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('account_login'))
    else:
        if request.method == 'POST':
            user_form = UserForm(request.POST, instance=request.user)
            profile_form = ProfileForm(request.POST, instance=request.user.profile)
            if user_form.is_valid() and profile_form.is_valid():
                profilesave = profile_form.save(commit=False)
                if 'image' in request.FILES:
                    profilesave.image = request.FILES['image']

                user_form.save()
                profile_form.save()
                #messages.success(request, _('Your profile was successfully updated!'))
                return redirect('posts:profile')
            else:
                messages.error(request, ('Please correct the error below.'))
        else:
            user_form = UserForm(instance=request.user)
            profile_form = ProfileForm(instance=request.user.profile)
        return render(request, 'posts/update_profile.html', {
            'user_form': user_form,
            'profile_form': profile_form
        })
def add_question(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('account_login'))
    else:
        if request.method == "POST":
            form = QuestionForm(request.POST)
            if form.is_valid():
                question = form.save(commit=False)
                question.user = request.user
                question.created_date = timezone.now()
                question.published_date = timezone.now()
                question.save()
                return redirect('posts:question_list')
        else:
            form = QuestionForm()
        return render(request, 'posts/add_question.html', {'form': form})


def question_list(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('account_login'))
    else:
        questions = Question.objects.order_by('published_date')
        #answers = Answer.objects.order_by('date')

        return render(request, 'posts/homenew.html', {'questions': questions})

def delete_question(request,pk):
    question = get_object_or_404(Question, pk=pk)
    question.delete()
    return redirect('posts:question_list')

def delete_answer(request,pk):
    answer = get_object_or_404(Answer,pk=pk)
    value = answer.question.pk
    answer.delete()
    return redirect('posts:question_detail',pk=value)

def update_question(request,pk):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('account_login'))
    else:
        print(pk)
        question = get_object_or_404(Question, pk=pk)
        print(question.pk)
        if request.method == 'POST':
            form = QuestionForm(request.POST, instance=question)

            if form.is_valid():
                #que = form.save(commit=False)
                #que.created_date = timezone.now()
                #que.published_date = timezone.now()

                form.save()

                return redirect('posts:question_detail', pk=pk)
            else:
                messages.error(request, ('Please correct the error below.'))
        else:
            form = QuestionForm(instance=question)

        return render(request, 'posts/add_question.html', {
            'form': form,

        })

def update_answer(request,pk):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('account_login'))
    else:
        print(pk)
        answer = get_object_or_404(Answer, pk=pk)
        print(answer.pk)
        if request.method == 'POST':
            form = AnswerForm(request.POST, instance=answer)

            if form.is_valid():
                #que = form.save(commit=False)
                #que.created_date = timezone.now()
                #que.published_date = timezone.now()

                form.save()

                return redirect('posts:question_detail', pk=answer.question.pk)
            else:
                messages.error(request, ('Please correct the error below.'))
        else:
            form = AnswerForm(instance=answer)

        return render(request, 'posts/add_question.html', {
            'form': form,

        })

def question_detail(request, pk):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('account_login'))
    else:
        question = get_object_or_404(Question, pk=pk)
        answers = Answer.objects.filter(question = question).order_by('date')
        return render(request, 'posts/post_detailnew.html', {'question': question, 'answers':answers})

def add_answer(request, pk):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('account_login'))
    else:
        question = get_object_or_404(Question, pk=pk)
        if request.method == "POST":
            form = AnswerForm(request.POST)
            if form.is_valid():
                answer = form.save(commit=False)
                answer.question = question
                answer.user = request.user
                answer.date = timezone.now()
                answer.save()
                return redirect('posts:question_detail', pk=pk)
        else:
            form = AnswerForm()
        return render(request, 'posts/add_answernew.html', {'form': form, 'question': question})

posts/templates/posts/add_answernew.html
{% extends 'posts/base.html' %}
{% load bootstrap3 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% block title %}Ask Lnmiit{% endblock %}
{% block static_files %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}" />
<script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

{% block body %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://bootswatch.com/cosmo/bootstrap.min.css">

            <div style="padding-top:50px;"> </div>
            <div class="col-md-offset-1 col-lg-offset-1 col-lg-10 col-md-10 col-sm-12 col-xs-12">
              <div class="panel panel-default">
                  <div class="panel-body">
                    <div class="media">
                          <div class="pull-left">
                              <a href="#">
                                  <img class="media-object img-circle" src="{{ user.profile.image.url }}" width="35px" height="35px" style="margin-left:3px; margin-right:-5px;">
                              </a>
                          </div>
                          <div class="media-body">

                          <form method="POST" class="post-form">{% csrf_token %}
                              {% bootstrap_form form %}







                          </div>
                      </div>
                      <hr>
                      <div class="pull-right post-button-submit">
                        {% buttons %}

                          <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "star" %} Submit
                          </button>
                        {% endbuttons %}
</form>
                      </div>

                  </div>
              </div>
                <hr>
              
            </div>
            {% endblock %}

posts/templates/posts/post_detailnew.html
{% extends 'posts/base.html' %}
{% block title %}Ask Lnmiit{% endblock %}
{% block static_files %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}" />
<script src="{% static 'js/profile.js' %}"></script>
{% endblock %}


{% block body %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://bootswatch.com/cosmo/bootstrap.min.css">

            <div style="padding-top:50px;"> </div>

            <div class="col-md-offset-1 col-lg-offset-1 col-lg-10 col-md-10 col-sm-12 col-xs-12">



                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="pull-left">
                            <a href="#">
                                <img class="media-object img-circle" src="{{ question.user.profile.image.url }}" width="50px" height="50px" style="margin-right:8px; margin-top:-5px;">
                            </a>
                        </div>
                        {% if question.user.username == user.username %}
                        <div class="pull-right btn-group-sm">
                          <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal"><i class="fa fa-trash-o" aria-hidden="true"></i> </button>
                          <div class="modal fade" id="myModal" role="dialog">
                          <div class="modal-dialog">


                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Delete Question</h4>
                              </div>
                              <div class="modal-body">
                                <p>Are you sure you want to delete this question?</p>
                              </div>
                              <div class="modal-footer">
                                <form action="{% url 'posts:delete_question' question.pk %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="song_id" value="{{ question.pk }}" />
                                    <button type="submit" class="btn btn-danger ">
                                        <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                    </button>
                                </form>
                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              </div>
                            </div>

                          </div>
                        </div>
                        <a href="{% url 'posts:update_question' pk=question.pk %}" class="btn btn-default btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> </a>
                        </div>
                        {% endif %}
                        <h4><a href="{% if user.username == question.user.username %}{% url 'posts:profile' %}{% else %}{% url 'posts:user_profile' username=question.user.username %}{% endif %}" style="text-decoration:none;"><strong>{{ question.user.username }}</strong></a> – <small><small><a  style="text-decoration:none; color:grey;"><i><i class="fa fa-clock-o" aria-hidden="true"></i> {{ question.published_date }}</i></a></small></small></h4>

                        <hr>
                        <div class="post-content">
                          <h1 style="font-size:30px;"><p><strong>{{ question.text }}</strong></h1><small style="color:grey;"><small>{{ question.details }}</small></small></p>


                        </div>
                        <hr>
                        <div>

                            <div class="text-center">
                                <p class="text-muted post-last" style="color:red;"><a  style="text-decoration:none; color:grey; letter-spacing: 5px;"><h4 class="whiteTextOverride"><strong>A    N    S    W    E    R   S</strong></a></h4></p>
                            </div>

                        </div>

                        <div>
                        <hr>
                            {% for answer in answers %}

                            <div class="post-content">
                                <div class="panel-default">
                                    <div class="panel-body">
                                      <hr>
                                        <div class="pull-left">
                                            <a href="#">
                                                <img class="media-object img-circle" src="{{ answer.user.profile.image.url }}" width="35px" height="35px" style="margin-right:8px; margin-top:-5px;">
                                            </a>
                                        </div>

                                        <div class="pull-right btn-group-sm">
                                          {% if answer.user.username == user.username %}
                                          <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal"><i class="fa fa-trash-o" aria-hidden="true"></i> </button>
                                          <div class="modal fade" id="myModal" role="dialog">
                                          <div class="modal-dialog">


                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                <h4 class="modal-title">Delete Answer</h4>
                                              </div>
                                              <div class="modal-body">
                                                <p>Are you sure you want to delete this answer?</p>
                                              </div>
                                              <div class="modal-footer">
                                                <form action="{% url 'posts:delete_answer' answer.pk %}" method="post" style="display: inline;">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="song_id" value="{{ answer.pk }}" />
                                                    <button type="submit" class="btn btn-danger ">
                                                        <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                                    </button>
                                                </form>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                              </div>
                                            </div>

                                          </div>
                                        </div>
                                            <a href="{% url 'posts:update_answer' pk=answer.pk %}" class="btn btn-default btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> </a>
                                            {% endif %}
                                          </div>

                                        <h4><a href="{% if user.username == answer.user.username %}{% url 'posts:profile' %}{% else %}{% url 'posts:user_profile' username=answer.user.username %}{% endif %}" style="text-decoration:none;"><strong>{{ answer.user.username }}</strong></a></h4>
                                        <hr>
                                        <div class="post-content">
                                         {{ answer.text }}
                                            <br><small><small><a  style="text-decoration:none; color:grey;"><i><i class="fa fa-clock-o" aria-hidden="true"></i> {{ answer.date }}</i></a></small></small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            {% endfor %}

                            <div class="post-content">
                                <div class="panel-default">
                                    <div class="panel-body">
                                        <div class="pull-left">
                                            <a href="#">
                                                <img class="media-object img-circle" src="{{ user.profile.image.url }}" width="35px" height="35px" style="margin-right:8px; margin-top:-5px;">
                                            </a>
                                        </div>
                                        <h4><a href="{% url 'posts:add_answer' pk=question.pk %}" style="text-decoration:none;"><strong>Add Your Answer</strong></a></h4>


                                    </div>
                                </div>
                            </div>
                            <hr>
                        </div>

                    </div>
                </div>
            </div>








{% endblock  %}

posts/templates/posts/profile.html
{% extends 'posts/base.html' %}{% block title %}Profile{% endblock %}
{% block static_files %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'profile.css' %}" />
<script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

{% block body %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://bootswatch.com/cosmo/bootstrap.min.css">

<div style="padding-top:50px;"> </div>
        <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="media">
                        <div align="center">
                            <img class="thumbnail img-responsive" src="{{ user.profile.image.url }}" width="300px" height="300px">
                        </div>
                        <div class="media-body">
                            <hr>
                            <h3><strong>Bio</strong></h3>
                            <p>{{ user.profile.bio }}</p>
                            <hr>

                            <h3><strong>Gender</strong></h3>
                            <p>{{ user.profile.gender }}</p>
                            <hr>
                            <h3><strong>Birthday</strong></h3>
                            <p>{{ user.profile.dob.date }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body test">
                    <span>
                        <h1 class="panel-title pull-left" style="font-size:30px;">{{ user.username }} <small>{{ user.email }}</small> </h1>
                        {% if user.is_authenticated %}
                        <div class="dropdown pull-right">
                          <a href="{% url 'posts:update_profile' %}">
                            <button class="btn btn-success" type="button" id="dropdownMenu1"  aria-haspopup="true" aria-expanded="true">
                                Update Profile


                            </button>
                          </a>

                        </div>
                        {% endif %}
                    </span>
                    <br><br>


                    <h1 class="panel-title pull-left" style="font-size:20px;">{{ user.first_name }} {{ user.last_name }}</h1>
                    <br>


                </div>
            </div>
            <ul class="nav nav-tabs">
              <li class="active"><a data-toggle="tab" href="#home">My Questions</a></li>
              <li><a data-toggle="tab" href="#menu1">My Answers</a></li>

            </ul>
            <div class="tab-content">
              <div id="home" class="tab-pane fade in active">



            {% for question in user.question_set.all %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="pull-left">
                        <a href="#">
                            <img class="media-object img-circle" src="{{ question.user.profile.image.url }}" width="50px" height="50px" style="margin-right:8px; margin-top:-5px;">
                        </a>
                    </div>
                    <h4><a href="{% if user.username == question.user.username %}{% url 'posts:profile' %}{% else %}{% url 'posts:user_profile' username=question.user.username %}{% endif %}" style="text-decoration:none;"><strong>{{ question.user.username }}</strong></a> – <small><small><a  style="text-decoration:none; color:grey;"><i><i class="fa fa-clock-o" aria-hidden="true"></i>{{ question.published_date }}</i></a></small></small></h4>

                    <hr>
                    <div class="post-content">

                        <h1 style="font-size:30px;"><p><a href="{% url 'posts:question_detail' pk=question.pk %}">{{ question.text }}</a></h1><small style="color:grey;"><small>{{ question.details }}</small></small></p>
                    </div>
                    <hr>
                    <div>

                        <div class="pull-left post-answer">

                        </div>
                        <br>
                    </div>


                </div>
            </div>
            {% endfor %}

          </div>
          <div id="menu1" class="tab-pane fade">



            {% for answer in user.answer_set.all %}
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="pull-left">
                        <a href="#">
                            <img class="media-object img-circle" src="{{ answer.question.user.profile.image.url }}" width="50px" height="50px" style="margin-right:8px; margin-top:-5px;">
                        </a>
                    </div>
                    <h4><a href="{% if user.username == answer.question.user.username %}{% url 'posts:profile' %}{% else %}{% url 'posts:user_profile' username=answer.question.user.username %}{% endif %}" style="text-decoration:none;"><strong>{{ answer.question.user.username }}</strong></a> – <small><small><a  style="text-decoration:none; color:grey;"><i><i class="fa fa-clock-o" aria-hidden="true"></i>{{ answer.question.published_date }}</i></a></small></small></h4>

                    <hr>
                    <div class="post-content">

                        <h1 style="font-size:30px;"><p><a href="{% url 'posts:question_detail' pk=answer.question.pk %}">{{ answer.question.text }}</a></h1><small style="color:grey;"><small>{{ answer.question.details }}</small></small></p>
                    </div>
                    <hr>
                    <div>

                        <div class="pull-left post-answer">

                        </div>
                        <br>
                    </div>


                </div>
            </div>
            {% endfor %}




            </div>

        </div>




        </div>

{% endblock %}